### ISSUE TITLE
the pdd command outputs just the assembly code

### ISSUE THREAD

**Issue by Harshiv-Patel** [wargio/r2dec-js#217]
OS : Windows 10 , arch x64
Radare2 version: 4.4.0 24350 @ windows-x86-64

So I built the source with `meson build` , `cd build` , and `meson compile` which completed without any errors,
Then I copied the whole folder (named `r2dec-js-4.4.0` ) to dir pointed by `radare2.exe -H R2_RDATAHOME`
Which in my case is 
`C:\Users\Harshiv\.local\share\radare2\`
The `r2pm\git` directory structure wasn't there, so I created it.
Copied the r2dec folder with built library file (under `r2dec-js-4.4.0\p\build\libcore_pdd.dll` )
To the created folder,

and opened my file of interest `r2 libmain.so`
Did `af` followed by `pdd` , and it printed the assembly output.
![cropped](https://user-images.githubusercontent.com/25936599/87877805-fefb1c80-c9fd-11ea-9ad6-a56aec60f325.png)

I also tried the cutter's "radar2/plugin" version of the core_pdd.dll, with same result.

Am I missing something here?

**Comment by Harshiv-Patel** [comment]
The so library is of arch armv7,Android

**Comment by wargio** [comment]
i think the library was not installed correctly. how did you install it?

**Comment by wargio** [comment]
`libcore_pdd.dll` needs to be copied into the r2 plugins folder.

**Comment by q8ing** [comment]
I opened an old issue regarding this in windows, still can't get it to work in windows without cutter, I installed the library correctly and everything is fine, but when I run pddf, It crashes without any reason.
Here is some pictures related to this problem, I am still using cutter instead of compiling it by myself, I compiled the source code with Mingw64. 
![1](https://user-images.githubusercontent.com/52950756/106661955-e1b12880-65b2-11eb-8b0d-f12c0861d87d.png)
![2](https://user-images.githubusercontent.com/52950756/106661978-e544af80-65b2-11eb-924d-55ad9db87c56.png)
![3](https://user-images.githubusercontent.com/52950756/106661987-e7a70980-65b2-11eb-9df1-a82bc9725208.png)
![4](https://user-images.githubusercontent.com/52950756/106661996-e970cd00-65b2-11eb-8bec-96c109d6bffe.png)



Wish you best luck :)

**Comment by trufae** [comment]
Is your radare compiled with the same compiler as the plugin? Are you using the ci builds from r2. I will add the ci job to build the mac, debian and windows plugins for r2dec. I dont have windows to test but i will test it in the ci and see if it works or not.

**Comment by wargio** [comment]
i feel like what @trufae said might be correct. looks like a version mismatch, but if it doesn't crash with `pdd?` then can be a bug on `r2dec` itself.
can you provide the `pddi` output? if not the binary?
If you do not want to share the binary here, you can find me on the radare telegram channel or you can send me an email.

**Comment by trufae** [comment]
See https://github.com/wargio/r2dec-js/pull/231

**Comment by q8ing** [comment]
I built them both using Microsoft visual studio 2019 (CL) instead of using mingw64 for building the plugin and visual studio 2019 for radare2.  A error message appeared instead of a sudden crash.

![11](https://user-images.githubusercontent.com/52950756/106701413-aab13600-65f7-11eb-9e62-58584fa27176.png)


My radare2 is built using two commands:
1- "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
2- python sys\meson.py --release --backend vs2019 --shared --install --prefix %cd%\dist --webui

My r2dec plugin is built using two commands:
1- meson C:\Users\root\.local\share\radare2\r2pm\git\r2dec-js\p
2- ninja

I moved core_pdd.dll to C:\Users\root\.local\share\radare2\plugins
and core_pdd.lib C:\Users\root\AppData\Local\Programs\radare2\dist\lib\plugins

C:\Users\root\Desktop>radare2 -H
R2_VERSION=5.1.0
R2_PREFIX=.
R2_MAGICPATH=C:\Users\root\AppData\Local\Programs\radare2\dist\share\magic
R2_INCDIR=C:\Users\root\AppData\Local\Programs\radare2\dist\include\libr
R2_LIBDIR=C:\Users\root\AppData\Local\Programs\radare2\dist\lib
R2_LIBEXT=dll
R2_RCONFIGHOME=C:\Users\root\.config\radare2
R2_RDATAHOME=C:\Users\root\.local\share\radare2
R2_RCACHEHOME=C:\Users\root\.cache\radare2
R2_LIBR_PLUGINS=C:\Users\root\AppData\Local\Programs\radare2\dist\lib\plugins
R2_USER_PLUGINS=C:\Users\root\.local\share\radare2\plugins
R2_USER_ZIGNS=C:\Users\root\.local\share\radare2\zigns

I created env variable R2DEC_HOME that points to C:\Users\root\.local\share\radare2

I also moved the entire r2dec-js folder to C:\Users\root\.local\share\radare2\r2pm\git
because I though maybe the problem is related to env variable that I created earlier.

Here is the compiled files.


[Files.zip](https://github.com/wargio/r2dec-js/files/5916224/Files.zip)


Thank you very much for your assistance :>

**Comment by wargio** [comment]
i'm not sure if that is a bug on r2dec or r2. if you run `aflj` on r2 does it crash ?

**Comment by q8ing** [comment]
No, It won't crash with aflj.

Here is some pictures:
![1](https://user-images.githubusercontent.com/52950756/106800492-93af2a00-6671-11eb-97e4-4f06f9832039.png)
![2](https://user-images.githubusercontent.com/52950756/106800500-9742b100-6671-11eb-8bde-f5ff80496eeb.png)
![3](https://user-images.githubusercontent.com/52950756/106800509-99a50b00-6671-11eb-8860-ddc8070916dd.png)
![4](https://user-images.githubusercontent.com/52950756/106800513-9c9ffb80-6671-11eb-8348-20d51f6bbb76.png)

[radare2.zip](https://github.com/wargio/r2dec-js/files/5921081/radare2.zip)
[plugin.zip](https://github.com/wargio/r2dec-js/files/5921088/plugin.zip)


I uploaded the entire build here with the plugin too, you can test them by yourself :)
Thank you very much.

**Comment by trufae** [comment]
Can you Try with the binaries generated in the ci

**Comment by q8ing** [comment]
Yeah, I tested your generated binaries (r2dec-5.1.0_w64.zip).

It generated the same error as above in the pictures.

**Comment by q8ing** [comment]
I installed radare2 using the installer (5.1.0) instead of compiling It by myself, moved .dll file and plugin directory to correct locations, after that I used pdd? 
Guess what?
It is showing the assembly code only instead of the plugin options.

**Comment by wargio** [comment]
can you share the binary?

**Comment by q8ing** [comment]
> can you share the binary?

I didn't compile anything by myself this time, I used the official releases available in repos, Here is the links:

https://github.com/radareorg/radare2/releases/download/5.1.0/radare2-5.1.0_w64.zip

https://github.com/radareorg/r2cutter/releases/download/0.1.1/r2cutter-0.1.1_w64.zip

https://github.com/wargio/r2dec-js/actions/runs/532391106#artifacts


For r2dec, I tested trufae compiled binary, still getting the same error.

**Comment by wargio** [comment]
i don't know what you are doing, but i can't even load the library with the artifacts, on windows.
https://github.com/radareorg/radare2/releases/download/5.1.0/radare2-5.1.0_w64.zip
https://github.com/wargio/r2dec-js/actions/runs/532391106#artifacts

**Comment by wargio** [comment]
![image](https://user-images.githubusercontent.com/561184/106925739-a9bff780-6710-11eb-964e-4f143ddabb0e.png)

**Comment by q8ing** [comment]
> ![image](https://user-images.githubusercontent.com/561184/106925739-a9bff780-6710-11eb-964e-4f143ddabb0e.png)
> 
> 

I didn't load the library, I just moved it to radare2 plugin folder, created env variable as mentioned in the instructions and used pdd? command.

**Comment by wargio** [comment]
yes, i did the same as you can see. but still, it doesn't work for me. i'll try again later.

**Comment by q8ing** [comment]
Here is a step by step for what I did, I uploaded the files too.

![1](https://user-images.githubusercontent.com/52950756/107095139-508fbb00-6819-11eb-8a07-0b793fb5625d.png)
![2](https://user-images.githubusercontent.com/52950756/107095144-52f21500-6819-11eb-9d04-e261d7e60f9b.png)
![3](https://user-images.githubusercontent.com/52950756/107095149-54234200-6819-11eb-88ce-9f09d9ec7b8c.png)
![4](https://user-images.githubusercontent.com/52950756/107095152-55546f00-6819-11eb-8282-9b2cc7ad4653.png)
![5](https://user-images.githubusercontent.com/52950756/107095160-571e3280-6819-11eb-8ac3-9a69848e894b.png)
![6](https://user-images.githubusercontent.com/52950756/107095167-584f5f80-6819-11eb-90db-69df8e368539.png)
![7](https://user-images.githubusercontent.com/52950756/107095172-5a192300-6819-11eb-9044-b42328f79cd6.png)
![8](https://user-images.githubusercontent.com/52950756/107095177-5c7b7d00-6819-11eb-8140-292fb9da7b10.png)
![9](https://user-images.githubusercontent.com/52950756/107095181-5f766d80-6819-11eb-8229-9e93342ba9e9.png)
![10](https://user-images.githubusercontent.com/52950756/107095188-61d8c780-6819-11eb-8873-9b8925598a83.png)
![11](https://user-images.githubusercontent.com/52950756/107095193-64d3b800-6819-11eb-9678-88cc11dafc69.png)
![12](https://user-images.githubusercontent.com/52950756/107095203-67361200-6819-11eb-9eae-4c576e3d876d.png)
![13](https://user-images.githubusercontent.com/52950756/107095208-69986c00-6819-11eb-9a73-717b8f35ee81.png)
[radare2-5.1.0_w64.zip](https://github.com/wargio/r2dec-js/files/5935638/radare2-5.1.0_w64.zip)
[r2dec-5.1.0_w64.zip.zip](https://github.com/wargio/r2dec-js/files/5935639/r2dec-5.1.0_w64.zip.zip)

look how cutter went through the same problem. I think windows version is not tested well :>

Thank you very much for your time.

**Comment by wargio** [comment]
This bug was fixed.
